[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day03"
path = "src/day03.rs"
